# -*- coding: utf-8 -*-
{
    "name": "Yorange",
    "version": "14.1.1.0",
    "summary": "Bubble and OKR",
    "author": "Lucio Valente",
    "sequence": -100,
    "description": """Bubble and OKR Management""",
    "category": "Hr",
    "website": "https://www.rapsodoo.com",
    "depends": ["mail", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/bubble_role_view.xml",
        "views/bubble_type_view.xml",
        "views/bubble_view.xml",
        "views/objective_view.xml",
        "views/okr_view.xml",
        "views/okr_result.xml",
        "views/okr_evaluation.xml",
        "views/okr_evaluation_type.xml",
        "wizard/wizard.xml",
        "wizard/wizard_view_bubble.xml",
        "wizard/wizard_suggest_kr.xml",
        "wizard/wizard_my_dashboard.xml",
        "data/data.xml",
        "views/menu.xml",
        "views/asset.xml",
    ],
    "qweb": ["static/src/xml/bubble_widget.xml"],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "OEEL-1",
}
