name: Lint and Auto-fix Python Code

on:
  push:
    branches: [ lint_branch ]
  pull_request:
    branches: [ lint_branch ]

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Sostituisci con la versione di Python del tuo progetto

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort autoflake

    - name: Fix code with Black
      run: |
        black .

    - name: Fix code with isort
      run: |
        isort .

    - name: Commit changes
      run: |
        git config --global user.name 'Lucio'
        git config --global user.email 'luciovalente81@gmail.com'
        git add -A
        git commit -m "Apply auto-fixes" || echo "No changes to commit"
        echo ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        git push 
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
