name: Lint and Auto-fix Python Code

on:
  push:
    branches: [ fix_correction ]
  pull_request:
    branches: [ fix_correction ]

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Sostituisci con la versione di Python del tuo progetto

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort

    - name: Fix code with Black
      run: |
        black .

    - name: Fix code with isort
      run: |
        isort .

    - name: Commit changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add -A
        git commit -m "Apply auto-fixes" || echo "No changes to commit"
        git push origin ${{ github.head_ref }}
